export const ReminderActionTypes={
    ADD_DAILY_REMINDER:"ADD_DAILY_REMINDER",
    ADD_ONCE_REMINDER:"ADD_ONCE_REMINDER",
    ADD_ANNUAL_REMINDER:"ADD_ANNUAL_REMINDER",
    REMOVE_REMINDER:"REMOVE_REMINDER",
    UPDATE_REMINDER:"UPDATE_REMINDER",
    REMOVE_ALL_REMINDERS:"REMOVE_ALL_REMINDERS",
}